Discover autoscaling group automatically
- Use instance id of the current node to find the autoscaling group
- Use peer urls when starting a new cluster
- Change PROXY_ASG to PROXY to enable running on a proxy node

diff --git a/etcd-aws-cluster b/etcd-aws-cluster
--- a/etcd-aws-cluster
+++ b/etcd-aws-cluster
@@ -2,7 +2,9 @@
 pkg="etcd-aws-cluster"
 version="0.5"
 etcd_peers_file_path="/etc/sysconfig/etcd-peers"
-region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)
+meta_url="http://169.254.169.254/latest"
+region=$(curl -s $meta_url/dynamic/instance-identity/document | jq --raw-output .region)
+
 if [[ ! $region ]]; then
     echo "$pkg: failed to get region"
     exit 1
@@ -12,7 +14,7 @@ fi
 client_port=${ETCD_CLIENT_PORT:-2379}
 server_port=${ETCD_SERVER_PORT:-2380}
 
-# ETCD API https://coreos.com/etcd/docs/2.0.11/other_apis.html
+# ETCD API https://coreos.com/etcd/docs/latest/members_apis.html
 add_ok=201
 already_added=409
 delete_ok=204
@@ -23,29 +25,33 @@ if [ -f "$etcd_peers_file_path" ]; then
     exit 0
 fi
 
-ec2_instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+ec2_instance_id=$(curl -s $meta_url/meta-data/instance-id)
 if [[ ! $ec2_instance_id ]]; then
     echo "$pkg: failed to get instance id from instance metadata"
     exit 2
 fi
 
-ec2_instance_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
+ec2_instance_ip=$(curl -s $meta_url/meta-data/local-ipv4)
 if [[ ! $ec2_instance_ip ]]; then
     echo "$pkg: failed to get instance IP address"
     exit 3
 fi
 
 # If we're in proxy mode we don't have to look this up and expect an env var
-if [[ ! $PROXY_ASG ]]; then
+if [[ ! $PROXY ]]; then
     etcd_proxy=off
-    asg_name=$(aws autoscaling describe-auto-scaling-groups --region $region | jq --raw-output ".[] | map(select(.Instances[].InstanceId | contains(\"$ec2_instance_id\"))) | .[].AutoScalingGroupName")
-    if [[ ! $asg_name ]]; then
-        echo "$pkg: failed to get the auto scaling group name"
-        exit 4
-    fi
 else
     etcd_proxy=on
-    asg_name=$PROXY_ASG
+fi
+
+asg_name=$(aws autoscaling describe-auto-scaling-instances \
+    --region $region \
+    --instance-ids $ec2_instance_id \
+    --max-items 1 \
+    | jq -r '.AutoScalingInstances[].AutoScalingGroupName')
+if [[ ! $asg_name ]]; then
+    echo "$pkg: failed to get the auto scaling group name"
+    exit 4
 fi
 
 etcd_client_scheme=${ETCD_CLIENT_SCHEME:-http}
@@ -54,7 +60,14 @@ echo "client_client_scheme=$etcd_client_scheme"
 etcd_peer_scheme=${ETCD_PEER_SCHEME:-http}
 echo "peer_peer_scheme=$etcd_peer_scheme"
 
-etcd_peer_urls=$(aws ec2 describe-instances --region $region --instance-ids $(aws autoscaling describe-auto-scaling-groups --region $region --auto-scaling-group-name $asg_name | jq '.AutoScalingGroups[0].Instances[] | select(.LifecycleState  == "InService") | .InstanceId' | xargs) | jq -r ".Reservations[].Instances | map(\"$etcd_client_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$client_port\")[]")
+etcd_peer_urls=$(aws ec2 describe-instances \
+    --region $region \
+    --instance-ids $(aws autoscaling describe-auto-scaling-groups \
+        --region $region \
+        --auto-scaling-group-name $asg_name \
+        --max-items 1 \
+        | jq '.AutoScalingGroups[].Instances[] | select(.LifecycleState  == "InService") | .InstanceId' | xargs) \
+        | jq -r ".Reservations[].Instances | map(\"$etcd_client_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$client_port\")[]")
 
 if [[ ! $etcd_peer_urls ]]; then
     echo "$pkg: unable to find members of auto scaling group"
@@ -94,14 +107,16 @@ if [[ $etcd_existing_peer_urls && $etcd_existing_peer_names != *"$ec2_instance_i
     echo "joining existing cluster"
 
     # eject bad members from cluster
-    peer_regexp=$(echo "$etcd_peer_urls" | sed 's/^.*https\{0,1\}:\/\/\([0-9.]*\):[0-9]*.*$/contains(\\"\/\/\1:\\")/' | xargs | sed 's/  */ or /g')
+    peer_regexp=$(echo "$etcd_peer_urls" \
+        | sed 's/^.*https\{0,1\}:\/\/\([0-9.]*\):[0-9]*.*$/contains(\\"\/\/\1:\\")/' \
+        | xargs | sed 's/  */ or /g')
     if [[ ! $peer_regexp ]]; then
         echo "$pkg: failed to create peer regular expression"
         exit 6
     fi
 
     echo "peer_regexp=$peer_regexp"
-    bad_peer=$(echo "$etcd_members" | jq --raw-output ".[] | map(select(.peerURLs[] | $peer_regexp | not )) | .[].id")
+    bad_peer=$(echo "$etcd_members" | jq -r ".[] | map(select(.peerURLs[] | $peer_regexp | not )) | .[].id")
     echo "bad_peer=$bad_peer"
 
     if [[ $bad_peer ]]; then
@@ -116,8 +131,10 @@ if [[ $etcd_existing_peer_urls && $etcd_existing_peer_names != *"$ec2_instance_i
     fi
 
     # If we're not a proxy we add ourselves as a member to the cluster
-    if [[ ! $PROXY_ASG ]]; then
-        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" | jq --raw-output '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')$(echo ",$ec2_instance_id=${etcd_peer_scheme}://${ec2_instance_ip}:$server_port")
+    if [[ ! $PROXY ]]; then
+        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" \
+            | jq -r '.[] | map(.name + "=" + .peerURLs[0]) | .[]' \
+            | xargs | sed 's/  */,/g')$(echo ",$ec2_instance_id=${etcd_peer_scheme}://${ec2_instance_ip}:$server_port")
         echo "etcd_initial_cluster=$etcd_initial_cluster"
         if [[ ! $etcd_initial_cluster ]]; then
             echo "$pkg: docker command to get etcd peers failed"
@@ -126,14 +143,17 @@ if [[ $etcd_existing_peer_urls && $etcd_existing_peer_names != *"$ec2_instance_i
 
         # join an existing cluster
         echo "adding instance ID $ec2_instance_id with IP $ec2_instance_ip"
-        status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} -o /dev/null -XPOST "$etcd_good_member_url/v2/members" -H "Content-Type: application/json" -d "{\"peerURLs\": [\"$etcd_peer_scheme://$ec2_instance_ip:$server_port\"], \"name\": \"$ec2_instance_id\"}")
+        status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} -o /dev/null -XPOST "$etcd_good_member_url/v2/members" \
+            -H "Content-Type: application/json" \
+            -d "{\"peerURLs\": [\"$etcd_peer_scheme://$ec2_instance_ip:$server_port\"], \"name\": \"$ec2_instance_id\"}")
         if [[ $status != $add_ok && $status != $already_added ]]; then
             echo "$pkg: unable to add $ec2_instance_ip to the cluster: return code $status."
             exit 9
         fi
     # If we are a proxy we just want the list for the actual cluster
     else
-        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" | jq --raw-output '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')
+        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" \
+            | jq -r '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')
         echo "etcd_initial_cluster=$etcd_initial_cluster"
         if [[ ! $etcd_initial_cluster ]]; then
             echo "$pkg: docker command to get etcd peers failed"
@@ -153,7 +173,7 @@ else
     # create a new cluster
     echo "creating new cluster"
 
-    etcd_initial_cluster=$(aws ec2 describe-instances --region $region --instance-ids $(aws autoscaling describe-auto-scaling-groups --region $region --auto-scaling-group-name $asg_name | jq .AutoScalingGroups[0].Instances[].InstanceId | xargs) | jq -r ".Reservations[].Instances | map(.InstanceId + \"=$etcd_peer_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$server_port\")[]" | xargs | sed 's/  */,/g')
+    etcd_initial_cluster=$etcd_peer_urls
     echo "etcd_initial_cluster=$etcd_initial_cluster"
     if [[ ! $etcd_initial_cluster ]]; then
         echo "$pkg: unable to get peers from auto scaling group"
