Use alpine 3.4 and script updates

diff --git a/etcd-aws-cluster b/etcd-aws-cluster
--- a/etcd-aws-cluster
+++ b/etcd-aws-cluster
@@ -1,14 +1,10 @@
 #! /bin/bash
+set -euo pipefail
+IFS=$'\n\t'
+
 pkg="etcd-aws-cluster"
 version="0.5"
 etcd_peers_file_path="/etc/sysconfig/etcd-peers"
-meta_url="http://169.254.169.254/latest"
-region=$(curl -s $meta_url/dynamic/instance-identity/document | jq --raw-output .region)
-
-if [[ ! $region ]]; then
-    echo "$pkg: failed to get region"
-    exit 1
-fi
 
 # Allow default client/server ports to be changed if necessary
 client_port=${ETCD_CLIENT_PORT:-2379}
@@ -19,92 +15,100 @@ add_ok=201
 already_added=409
 delete_ok=204
 
-#if the script has already run just exit
+# proxy mode variable to be changed during execution or default is assumed
+[[ -z ${PROXY:-} ]] && etcd_proxy=off || etcd_proxy=on
+
+# Allow changing default client/peer scheme
+etcd_client_scheme=${ETCD_CLIENT_SCHEME:-http}
+
+etcd_peer_scheme=${ETCD_PEER_SCHEME:-http}
+
+# These will be manipulated by the script in order to generate the environemt
+# variables necessary to bootstrap the etcd cluster
+etcd_initial_cluster=
+etcd_existing_peer_urls=
+etcd_existing_peer_names=
+etcd_good_member_url=
+
+# if the script has already run just exit
 if [ -f "$etcd_peers_file_path" ]; then
     echo "$pkg: etcd-peers file $etcd_peers_file_path already created, exiting"
     exit 0
 fi
 
-ec2_instance_id=$(curl -s $meta_url/meta-data/instance-id)
-if [[ ! $ec2_instance_id ]]; then
-    echo "$pkg: failed to get instance id from instance metadata"
-    exit 2
-fi
+# The metadata request should always return something.
+# We also add a timeout and print the error even in silent mode
+function aws_data() {
+    [[ -z $1 ]] && echo "path is required to request meta data" && exit 1
+    local url="http://169.254.169.254/latest/$1"
+    result=$(curl -sSL -m 5 $url)
+    [[ -z $result ]] && echo "empty metadata from $url" && exit 2
+    echo $result
+}
 
-ec2_instance_ip=$(curl -s $meta_url/meta-data/local-ipv4)
-if [[ ! $ec2_instance_ip ]]; then
-    echo "$pkg: failed to get instance IP address"
-    exit 3
-fi
+region=$(aws_data dynamic/instance-identity/document | jq --raw-output .region)
 
-# If we're in proxy mode we don't have to look this up and expect an env var
-if [[ ! $PROXY ]]; then
-    etcd_proxy=off
-else
-    etcd_proxy=on
-fi
+ec2_instance_id=$(aws_data meta-data/instance-id)
 
-asg_name=$(aws autoscaling describe-auto-scaling-instances \
-    --region $region \
-    --instance-ids $ec2_instance_id \
-    --max-items 1 \
-    | jq -r '.AutoScalingInstances[].AutoScalingGroupName')
-if [[ ! $asg_name ]]; then
-    echo "$pkg: failed to get the auto scaling group name"
-    exit 4
-fi
+ec2_instance_ip=$(aws_data meta-data/local-ipv4)
 
-etcd_client_scheme=${ETCD_CLIENT_SCHEME:-http}
-echo "client_client_scheme=$etcd_client_scheme"
-
-etcd_peer_scheme=${ETCD_PEER_SCHEME:-http}
-echo "peer_peer_scheme=$etcd_peer_scheme"
-
-etcd_peer_urls=$(aws ec2 describe-instances \
-    --region $region \
-    --instance-ids $(aws autoscaling describe-auto-scaling-groups \
+# Get current instance ASG peers
+function asg_peers() {
+    local asg_name=$(aws autoscaling describe-auto-scaling-instances \
         --region $region \
-        --auto-scaling-group-name $asg_name \
+        --instance-ids $ec2_instance_id \
         --max-items 1 \
-        | jq '.AutoScalingGroups[].Instances[] | select(.LifecycleState  == "InService") | .InstanceId' | xargs) \
-        | jq -r ".Reservations[].Instances | map(\"$etcd_client_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$client_port\")[]")
+        | jq -r '.AutoScalingInstances[].AutoScalingGroupName')
 
-if [[ ! $etcd_peer_urls ]]; then
-    echo "$pkg: unable to find members of auto scaling group"
-    exit 5
-fi
-
-echo "etcd_peer_urls=$etcd_peer_urls"
-
-etcd_existing_peer_urls=
-etcd_existing_peer_names=
-etcd_good_member_url=
-
-for url in $etcd_peer_urls; do
-    case "$url" in
-        # If we're in proxy mode this is an error, but unlikely to happen?
-        *$ec2_instance_ip*) continue;;
-    esac
-
-    etcd_members=$(curl $ETCD_CURLOPTS -f -s $url/v2/members)
-
-    if [[ $? == 0 && $etcd_members ]]; then
-        etcd_good_member_url="$url"
-		echo "etcd_members=$etcd_members"
-        etcd_existing_peer_urls=$(echo "$etcd_members" | jq --raw-output .[][].peerURLs[0])
-		etcd_existing_peer_names=$(echo "$etcd_members" | jq --raw-output .[][].name)
-	break
+    if [[ -z $asg_name ]]; then
+        echo "No AutoScalingGroup for instace=$ec2_instance_id in region=$region"
+        exit 3
     fi
-done
 
-echo "etcd_good_member_url=$etcd_good_member_url"
-echo "etcd_existing_peer_urls=$etcd_existing_peer_urls"
-echo "etcd_existing_peer_names=$etcd_existing_peer_names"
+    local peer_urls=$(aws ec2 describe-instances
+        --region $region \
+        --instance-ids $(aws autoscaling describe-auto-scaling-groups \
+            --region $region \
+            --auto-scaling-group-name $asg_name \
+            --max-items 1 \
+            | jq '.AutoScalingGroups[].Instances[] | select(.LifecycleState  == "InService") | .InstanceId' | xargs) \
+            | jq -r ".Reservations[].Instances | map(\"$etcd_client_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$client_port\")[]")
+    if [[ -z $peer_urls ]]; then
+        echo "Instance has no peers in current AutoScalingGroup"
+        exit 4
+    fi
+    echo $peer_urls
+}
+
+etcd_peer_urls=asg_peers
+
+function scurlf() {
+    echo $(curl -sSL -f -m 10 "$*")
+}
+
+function members() {
+    set +e
+    for url in $etcd_peer_urls; do
+        case "$url" in
+            # If we're in proxy mode this is an error, but unlikely to happen?
+            *$ec2_instance_ip*) continue;;
+        esac
+
+        etcd_members=$(scurlf $url/v2/members)
+
+        if [[ $? == 0 && ! -z $etcd_members ]]; then
+            etcd_good_member_url="$url"
+            etcd_existing_peer_urls=$(echo "$etcd_members" | jq --raw-output .[][].peerURLs[0])
+            etcd_existing_peer_names=$(echo "$etcd_members" | jq --raw-output .[][].name)
+        break
+        fi
+    done
+    set -e
+}
 
 # if I am not listed as a member of the cluster assume that this is a existing cluster
 # this will also be the case for a proxy situation
 if [[ $etcd_existing_peer_urls && $etcd_existing_peer_names != *"$ec2_instance_id"* ]]; then
-    echo "joining existing cluster"
 
     # eject bad members from cluster
     peer_regexp=$(echo "$etcd_peer_urls" \
@@ -112,52 +116,46 @@ if [[ $etcd_existing_peer_urls && $etcd_existing_peer_names != *"$ec2_instance_i
         | xargs | sed 's/  */ or /g')
     if [[ ! $peer_regexp ]]; then
         echo "$pkg: failed to create peer regular expression"
-        exit 6
+        exit 5
     fi
 
-    echo "peer_regexp=$peer_regexp"
     bad_peer=$(echo "$etcd_members" | jq -r ".[] | map(select(.peerURLs[] | $peer_regexp | not )) | .[].id")
-    echo "bad_peer=$bad_peer"
 
     if [[ $bad_peer ]]; then
         for bp in $bad_peer; do
-            echo "removing bad peer $bp"
-            status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} "$etcd_good_member_url/v2/members/$bp" -XDELETE)
+            status=$(scurlf -w %{http_code} "$etcd_good_member_url/v2/members/$bp" -XDELETE)
             if [[ $status != $delete_ok ]]; then
                 echo "$pkg: ERROR: failed to remove bad peer: $bad_peer, return code $status."
-                exit 7
+                exit 6
             fi
         done
     fi
 
     # If we're not a proxy we add ourselves as a member to the cluster
-    if [[ ! $PROXY ]]; then
-        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" \
+    if [[ -z $PROXY ]]; then
+        etcd_initial_cluster=$(scurlf "$etcd_good_member_url/v2/members" \
             | jq -r '.[] | map(.name + "=" + .peerURLs[0]) | .[]' \
             | xargs | sed 's/  */,/g')$(echo ",$ec2_instance_id=${etcd_peer_scheme}://${ec2_instance_ip}:$server_port")
-        echo "etcd_initial_cluster=$etcd_initial_cluster"
         if [[ ! $etcd_initial_cluster ]]; then
-            echo "$pkg: docker command to get etcd peers failed"
-            exit 8
+            echo "$pkg: unable to get peers"
+            exit 7
         fi
 
         # join an existing cluster
-        echo "adding instance ID $ec2_instance_id with IP $ec2_instance_ip"
-        status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} -o /dev/null -XPOST "$etcd_good_member_url/v2/members" \
+        status=$(scurlf -w %{http_code} -o /dev/null -XPOST "$etcd_good_member_url/v2/members" \
             -H "Content-Type: application/json" \
             -d "{\"peerURLs\": [\"$etcd_peer_scheme://$ec2_instance_ip:$server_port\"], \"name\": \"$ec2_instance_id\"}")
         if [[ $status != $add_ok && $status != $already_added ]]; then
             echo "$pkg: unable to add $ec2_instance_ip to the cluster: return code $status."
-            exit 9
+            exit 8
         fi
     # If we are a proxy we just want the list for the actual cluster
     else
-        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" \
+        etcd_initial_cluster=$(scurlf "$etcd_good_member_url/v2/members" \
             | jq -r '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')
-        echo "etcd_initial_cluster=$etcd_initial_cluster"
         if [[ ! $etcd_initial_cluster ]]; then
-            echo "$pkg: docker command to get etcd peers failed"
-            exit 8
+            echo "$pkg: unable to retrieve initial cluster for proxy"
+            exit 9
         fi
     fi
 
@@ -171,8 +169,6 @@ EOF
 # otherwise I was already listed as a member so assume that this is a new cluster
 else
     # create a new cluster
-    echo "creating new cluster"
-
     etcd_initial_cluster=$etcd_peer_urls
     echo "etcd_initial_cluster=$etcd_initial_cluster"
     if [[ ! $etcd_initial_cluster ]]; then
